version: '3.1'

services:

  db:
    image: postgres
    restart: always
    command: postgres -c 'max_connections=200'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reactive
    ports:
      - "5432:5432"
